ToDoApp/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoApp.Models
{
    public class ToDo
    {

        public int Id { get; set; }

        public string Description { get; set; }

        public bool isDone { get; set; }

        public virtual ApplicationUser User { get; set; }

    }
}

ToDoApp/Controllers/ToDoesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class ToDoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ToDoes
        public ActionResult Index()
        {
            return View();
        }

        private IEnumerable<ToDo> getMyToDoes ()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);

            IEnumerable<ToDo> myToDoes = db.ToDos.ToList().Where(x => x.User == currentUser);

            int completeCount = 0;

            foreach (ToDo toDo in myToDoes)
            {
                if (toDo.isDone)
                {
                    completeCount++;
                }
            }

            ViewBag.Percent = Math.Round(100f * ((float)completeCount / (float)myToDoes.Count()));

            return myToDoes;
        }

        

        public ActionResult getCompleted() {

            IEnumerable<ToDo> myToDoes = getMyToDoes();

            int completeCount = 0;

            foreach (ToDo toDo in myToDoes)
            {
                if (toDo.isDone)
                {
                    completeCount++;
                }
            }

            int completed = Convert.ToInt32(Math.Round(100f * ((float)completeCount / (float)myToDoes.Count())));

            return Json(completed, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BuildToDoTable()
        {
            return PartialView("_ToDoTable", getMyToDoes());
        }

        // GET: ToDoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }

        // GET: ToDoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToDoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,isDone")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                toDo.User = currentUser;
                db.ToDos.Add(toDo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(toDo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "Id,Description")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                toDo.User = currentUser;
                toDo.isDone = false;
                db.ToDos.Add(toDo);
                db.SaveChanges();
            }

            return PartialView("_ToDoTable", getMyToDoes());
        }

        // GET: ToDoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            
            if (toDo == null)
            {
                return HttpNotFound();
            }

            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);

            if (toDo.User != currentUser) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(toDo);
        }

        // POST: ToDoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,isDone")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toDo);
        }

        [HttpPost]
        public ActionResult AJAXEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.isDone = value;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_ToDoTable", getMyToDoes());
            }
        }

        // GET: ToDoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }

        // POST: ToDoes/Delete/5
        [HttpPost]
        public ActionResult AJAXDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {

                db.ToDos.Remove(toDo);
                db.SaveChanges();
                return PartialView("_ToDoTable", getMyToDoes());
            }
   
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToDoApp/Views/ToDoes/Create.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDone)
                    @Html.ValidationMessageFor(model => model.isDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoApp/Views/ToDoes/Delete.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToDoApp/Views/ToDoes/Details.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToDoApp/Views/ToDoes/Edit.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDone)
                    @Html.ValidationMessageFor(model => model.isDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoApp/Views/ToDoes/Index.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Index";
}

<h2>My ToDo List</h2>

<div id="progressBar">
	<div class="progress">
		<div class="progress-bar" role="progressbar" aria-valuenow="" aria-valuemin="0" aria-valuemax="100"></div>
	</div>
<div id="tableDiv"></div>

<div id="toDoForm">
	@using (Ajax.BeginForm("AJAXCreate", "ToDoes",
				new AjaxOptions
				{
					InsertionMode = InsertionMode.Replace,
					HttpMethod = "POST",
					UpdateTargetId = "tableDiv",
					OnSuccess = "ClearInputField"
				}

			))
	{
		<div class="form-group">
			@Html.AntiForgeryToken()

			@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
		</div>
	}
</div>

@section Scripts {

	<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
	<script src="~/Scripts/Custom_Scripts/BuildTable.js"></script>
	<script src="~/Scripts/Custom_Scripts/GenerateProgressBar.js"></script>
	<script>
		generate();
	</script>
	@Scripts.Render("~/bundles/jqueryval ") 

	<script type="text/javascript">

		function ClearInputField() {
			$("#Description").val("");


			generate();
		
			//$.ajax({
			//	url: '/ToDoes/getCompleted',
			//	success: function (result) {

			//		if (result == 100) {
			//			$('#progressBar .progress div').toggleClass('progress-bar progress-bar-success');
			//		}

			//		if (result < 100) {
			//			$('#progressBar .progress div').addClass('progress-bar').removeClass('progress-bar-success');
			//		}


			//		$('.progress-bar').each(function () {
			//			var bar_value = result + '%';
			//			$(this).text(bar_value);
			//			$(this).animate({ width: bar_value }, { duration: 50 });
			//		});

			//		$('.progress-bar-success').each(function () {
			//			var bar_value = result + '%';
			//			$(this).text(bar_value);
			//			$(this).animate({ width: bar_value }, { duration: 50 });
			//		});
			//	}

			//});
		}

	</script>


}

ToDoApp/Views/ToDoes/_ProgressBar.cshtml
<div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>

ToDoApp/Views/ToDoes/_ToDoTable.cshtml
@model IEnumerable<ToDoApp.Models.ToDo>

@*<div id="progressBar">
	<div class="progress">
		<div class="
		@if (@ViewBag.Percent == 100)
		{
			@MvcHtmlString.Create("progress-bar-success");
		} else {
			@MvcHtmlString.Create("progress-bar");
		}
		" role="progressbar" aria-valuenow="@ViewBag.Percent" aria-valuemin="0" 
			 aria-valuemax="100" >@(ViewBag.Percent)%</div>
	</div>
</div>*@


	<table class="table table-striped">


		@foreach (var item in Model)
		{
			<tr>
				<td id="@item.Id" class="itemDescription">
					@if (!item.isDone)
					{
						@Html.DisplayFor(modelItem => item.Description)
					}
					else
					{
						<div class="completedToDo">
							@Html.DisplayFor(modelItem => item.Description)
						</div>
					}

				</td>
				<td>
					@Html.CheckBoxFor(modelItem => item.isDone, new { id = item.Id, @class = "ActiveCheck" })
				</td>
				<td>
					@Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
					@Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
					
					<button id="@item.Id" class="btn btn-danger delete-row">Delete</button>
			</td>
			</tr>
		}

	</table>

<script src="~/Scripts/Custom_Scripts/GenerateProgressBar.js"></script>
<script src="~/Scripts/Custom_Scripts/CkeckBoxListener.js"></script>
<script src="~/Scripts/Custom_Scripts/Delete.js"></script>

@*<script src="~/Scripts/Custom_Scripts/EditDescription.js"></script>*@